name: Create Release on Tag Push

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout 主项目
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Get CHANGELOGS
        run: python ./scripts/release_note.py
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: result.txt
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'dev') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Update npm
        run: npm install -g npm@11.7.0

      - name: Setup yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build for production
        run: |
          yarn build
        env:
          TSC_COMPILE_ON_ERROR: true
          ESLINT_NO_DEV_ERRORS: true

      - name: publish on npm
        if: ${{ ! (contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'dev')) }}
        run: npm publish --provenance